### ISSUE TITLE
Обращение к Дмитрию

### ISSUE THREAD

**Issue by Whisperes** [dmitryy/moex-bonds#1]
Дмитрий, день добрый,

Увидел ваш проект и решил поддержать морально в вашем начинании. Создать калькулятор бондов давно пора, ибо ни сбондс, ни русбондс уже неактуальны в силу отсутствия западных практик. Надеюсь, ваш проект выйдет в свет.

Было бы интересно с вами поделиться рядом идей для сайта. Если вы не против, то найдите меня в телеграме по нику @Whisperes.

**Comment by dmitryy** [comment]
Добрый день, всегда открыт к новым идеям и помощи. У самого есть много идей, но не хватает рук для реализации.
